import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/Components/Provider'
import Navbar2 from '@/Components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbar2></Navbar2>
        {children}
        </Provider>
        </body>
    </html>
  )
}
